version: '3'

services:
  db:
    image: postgres:12.3-alpine
    environment:
      POSTGRES_DB: 'nodecker'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  web:
    build: .
    depends_on:
      - db
    volumes:
      - ./:/app
    ports:
      - '5000:5000'
